<?php
return [
    'valid_exact_val'           => 'El valor del campo ({field}) debe ser igual a ({param}).',
    'valid_max_val'             => 'El valor del campo ({field}) debe ser menor a ({param}).',
    'valid_min_val'             => 'El valor del campo ({field}) debe ser mayor a ({param}).',
    'valid_exact_length'        => 'La cantidad de caracteres del campo ({field}) debe ser igual a ({param}).',
    'valid_max_length'          => 'La cantidad de caracteres del campo ({field}) debe ser menor a ({param}).',
    'valid_min_length'          => 'La cantidad de caracteres del campo ({field}) debe ser mayor a ({param}).',
    'valid_min_size'            => 'El tama&ntilde;o del archivo del campo ({field}) no debe ser menor a ',
    'valid_max_size'            => 'El tama&ntilde;o del archivo del campo ({field}) no debe superar los ',
    
    'valid_required'            => 'El campo ({field}) es requerido.',
    'valid_json'                => 'Los datos del campo ({field}) no se recibieron de forma correcta.',
    'valid_custom'              => 'El campo ({field}) no es v&aacute;lido.',
    'valid_unique'              => 'El valor ({value}) del campo ({field}) ya existe y no puede repetirse.',
    'valid_upload'              => 'No se pudo subir el archivo:',
    'valid_extension'           => 'No se admite la extensi&oacute;n ({value}), solo se admiten las extensiones ({param}).',
    'valid_required_either'     => 'El campo ({field}) es requerido junto con el campo ({param}).',
    'valid_email'               => 'El campo ({field}) debe ser un E-mail v&aacute;lido.',
    'valid_url'                 => 'El campo ({field}) debe ser una URL v&aacute;lida.',
    'valid_options'             => 'El campo ({field}) no admite la opci&oacute;n ({value}).',
    'valid_compare'             => 'El campo ({field}) debe coincidir con ({param})',
    
    'valid_date'                => 'La fecha  del campo ({field}) debe ser una fecha v&aacute;lida.',
    'valid_max_date'            => 'La fecha del campo ({field}) debe ser anterior a',
    'valid_min_date'            => 'La fecha del campo ({field}) debe ser posterior a',
    
    'valid_upload_error_' . UPLOAD_ERR_INI_SIZE    => 'El peso del archivo del campo ({field}) supera el limite del servidor.',
    'valid_upload_error_' . UPLOAD_ERR_FORM_SIZE   => 'El peso del archivo del campo ({field}) supera el limite impuesto por el formulario.',
    'valid_upload_error_' . UPLOAD_ERR_PARTIAL     => 'El archivo del campo ({field}) fue parcialmente subido, intente nuevamente.',
    'valid_upload_error_' . UPLOAD_ERR_NO_FILE     => 'El archivo del campo ({field}) no se subi&oacute; al servidor.',
    'valid_upload_error_' . UPLOAD_ERR_NO_TMP_DIR  => 'Falta la carpeta temporal.',
    'valid_upload_error_' . UPLOAD_ERR_CANT_WRITE  => 'No se pudo escribir el fichero en el disco.',
    'valid_upload_error_' . UPLOAD_ERR_EXTENSION   => 'El archivo es potencialmente peligroso para el sistema.',
    
    'valid_string'              => 'El campo ({field}) no admite:',
    'valid_string_symbols'      => 's&iacute;mbolos como (\\ [ ^)',
    'valid_string_quotes'       => 'comillas',
    'valid_string_punctuation'  => 's&iacute;mbolos de pregunta y admiraci&oacute;n',
    'valid_string_commas'       => 'comas',
    'valid_string_dots'         => 'puntos',
    'valid_string_mid_strips'   => 'gui&oacute;nes medios',
    'valid_string_low_strips'   => 'gui&oacute;nes bajos',
    'valid_string_spaces'       => 'espacios en blanco',
    'valid_string_numbers'      => 'n&uacute;meros',
    'valid_string_alpha'        => 'letras',
];